version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native interface
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: mysecret
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-database.sql
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  clickhouse-data:
  clickhouse-logs:
  redis-data:
